apiVersion: azure.microsoft.com/v1alpha1
kind: MySQLFirewallRule
metadata:
  name: az-k8s-mysql-frwl-rl
spec:
  resourceGroup: az-k8s-operator
  server: az-k8s-mysql-server
  startIpAddress: 0.0.0.0
  endIpAddress: 255.255.255.255
