apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-cm
  namespace: default
data:
  WORDPRESS_DB_NAME: az-k8s-mysql-db
  WORDPRESS_DEBUG: "1"
  WORDPRESS_CONFIG_EXTRA: |
    define('WP_CACHE', true );
    define('WP_REDIS_HOST', 'redis-service');
