apiVersion: v1
kind: Service
metadata:
  name: wp-service
  namespace: default
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
